### ISSUE TITLE
Regarding benchmark 

### ISSUE THREAD

**Issue by nikitamehrotra12** [SE-Stuttgart/clone-study#1]
Hi,

I am not able to access the clone pairs that were released as a benchmark. Can you please help me with this. The benchmark folder here and on zenodo is empty.

Thanks in advance.

**Comment by wagnerst** [comment]
Hi,

no, they are not empty. See, for example, here: https://github.com/SE-Stuttgart/clone-study/blob/master/8_benchmark/C/1a_data_low/full/left.c
